QLNhaSach/QLNhaSach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ # what view connects to the url pattern
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

QLNhaSach/book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),

    path('update_item/', views.updateItem, name='update_item'),
    path('customer_info/', views.customer_info, name='information'),

    
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),


    # path('user/', views.userPage, name='user-page'),

    # path('account/', views.accountSetting, name='account'),

    path('book/<str:pk>/', views.book_details, name='book'), # xem chi tiết sách
    # path('customer/<str:pk_test>', views.customer, name='customer'),

    path('book_entry/', views.book_entry, name='book_entry'),
    # path('create_book/<str:pk>', views.createBook, name='create_Book'),
    # path('update_book/<str:pk>', views.updateBook, name='update_Book'),
    # path('delete_book/<str:pk>', views.deleteBook, name='delete_Book'),

    path('review_invoice/<str:pk>/', views.reviewInvoice, name='review_invoice'),

    path('list_invoice/', views.listInvoice, name='list_invoice'),

    path('debt_report/', views.debt_report, name='debt_report'),
    path('pay_debt/', views.pay_debt, name='pay_debt'),
    path('inventory_report/', views.inventory_report, name='inventory_report'),
    path('create_invoice/', views.create_invoice, name='create_invoice'),
    path('success/', views.success, name='success'),
]

QLNhaSach/book/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.utils import timezone

# Create your models here.
class Person(models.Model):
    class Meta:
        verbose_name_plural = 'Thành viên'
        
    # list_chucvu = (
	# 		('nhân viên', 'nhân viên'),
	# 		('thủ kho', 'thủ kho'),
    #         ('chủ nhà sách', 'chủ nhà sách'),
    #         ('khách hàng', 'khách hàng')
	# 		) 
    id = models.CharField(max_length=100, primary_key=True, editable=True)
    ho_ten = models.CharField('Họ tên', max_length=100, null=True)
    ngay_sinh = models.DateField('Ngày sinh', null=True, editable=True)
    so_dien_thoai = models.CharField('Số điện thoại', max_length=13, null=True)
    dia_chi = models.CharField('Địa chỉ', max_length=1000, null=True)
    email = models.CharField('Email', max_length=50, null=True)
    # chuc_vu = models.CharField('Chức vụ', max_length=100, null=True, choices=list_chucvu)
    profile_pic = models.ImageField(default="profile1.png", null=True)
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE) # a user can have 1 customer, a customer have a user
    
    def __str__(self):
        return self.id

    @property
    def get_group_name(self):
        query_set = Group.objects.filter(user = self.user)
        if not query_set:
            query_set = ''
        else:
            query_set = query_set[0].name.capitalize()

        return query_set

    @property
    def get_debt(self):
        if 'kh' in self.id: 
            s = 0
            cac_hd = HoaDon.objects.filter(khach_hang=self)
            # print(cac_hd)
            for hd in cac_hd:
                if hd.tong_tien != hd.da_tra and hd.da_tra != -1:
                    s += hd.tong_tien - hd.da_tra
                    # print(hd, s)
            return s
    
class Sach(models.Model):
    ten_sach = models.CharField('Tên sách', max_length=100, null=True)
    ngay_nhap = models.DateField('Ngày nhập', null=True, default=timezone.now)
    so_luong = models.PositiveIntegerField('Số lượng', null=True)
    the_loai = models.CharField('Thể loại', max_length=100, null=True)
    tac_gia = models.CharField('Tác giả', max_length=100, null=True)
    don_gia = models.PositiveBigIntegerField('Đơn giá', null=True)
    gia_ban = models.PositiveBigIntegerField('Giá bán', null=True)
    nha_xuat_ban = models.CharField('Nhà xuất bản', max_length=100, null=True)
    nam_xuat_ban = models.PositiveIntegerField('Năm xuất bản', null=True)
    nguoi_nhap = models.ForeignKey(Person, verbose_name= 'Người nhập', null=True, on_delete=models.PROTECT) 
    anh_sach = models.ImageField(default="static/placeholder.png",null=True, blank=True)
    mo_ta = models.TextField("Mô tả ngắn", max_length=1000, null=True, blank=True)
    
    def __str__(self):
        return f'{self.ten_sach}_{self.ngay_nhap}'
    
    def get_absolute_url(self):
        return f"/book/{self.id}/" 

    @property
    def imageURL(self):
        try:
            url = self.anh_sach.url
        except:
            url = ''
        return url

    @property
    def get_book_quantity(self):
        return self.so_luong-20
    
    @property
    def get_name(self):
        return self.ten_sach
        
    class Meta: # vì django ko cho tạo PK 2 thuộc tính nên làm cách này
        unique_together = ('id', 'ngay_nhap',)
        verbose_name_plural = "Sách"

class NhapSach(models.Model):
    ten_sach = models.CharField('Tên sách', max_length=100, null=True)
    ngay_nhap = models.DateField('Ngày nhập', null=True, default=timezone.now)
    so_luong = models.PositiveIntegerField('Số lượng', null=True)
    
    def __str__(self):
        return f'{self.ten_sach}_{self.ngay_nhap}'
    class Meta:
        verbose_name_plural = 'Nhập sách'  
          
class HoaDon(models.Model):
    class Meta:
        verbose_name_plural = 'Hóa đơn'
        
    pttt = (
            ('Thẻ ngân hàng', 'Thẻ ngân hàng'),
            ('Tiền mặt', 'Tiền mặt'),
            )
    id_HD = models.CharField('Mã hóa đơn', max_length=100, primary_key=True, default= 'HD_', editable=True)
    ngay_lap_HD = models.DateTimeField('Ngày lập hóa đơn', null=True)
    tong_tien = models.FloatField('Tổng tiền', null=True, default=0, editable=True)
    nguoi_lap_HD = models.ForeignKey(Person, verbose_name='Nhân viên', null=True, blank=True, related_name="nhan_vien", on_delete=models.PROTECT)
    khach_hang = models.ForeignKey(Person, verbose_name='Khách hàng', null=True, blank=True, related_name="khach_hang", on_delete=models.PROTECT)
    phuong_thuc_thanh_toan = models.CharField('Phương thức thanh toán', max_length=100, null=False, choices=pttt)
    da_tra = models.FloatField('Đã trả', null=True, default=0, editable=True)
    
    def __str__(self):
        return self.id_HD
    
    def clean(self):
        # constraint: chỉ nợ tối đa 20.000d
        if self.tong_tien is not None and self.da_tra is not None and self.tong_tien - self.da_tra > 20000:
            raise ValidationError('khách hàng chỉ được phép nợ tối đa 20.000d')

    @property 
    def get_cart_total(self):
        cac_mat_hang = self.chitiethoadon_set.all()
        tong_tien = sum([mh.get_total for mh in cac_mat_hang])
        return tong_tien

    @property
    def get_cart_items(self):
        cac_mat_hang = self.chitiethoadon_set.all()
        total = sum([mh.so_luong for mh in cac_mat_hang])
        return total

class ChiTietHoaDon(models.Model): # 1 lần nhập 1 sách
    # cthd của hóa đơn nào
    hoa_don = models.ForeignKey(HoaDon, verbose_name='Hóa đơn', on_delete=models.PROTECT)
    # khach_hang = models.ForeignKey(Person, verbose_name='Khách hàng', on_delete=models.PROTECT)
    sach = models.ForeignKey(Sach, verbose_name='Sách mua', on_delete=models.PROTECT)
    so_luong = models.PositiveIntegerField('Số lượng', null=True, default=0, editable=True)
    # giá bán 1 sản phẩm
    # gia_ban = models.FloatField(null=True)
    
    def __str__(self):
        return self.hoa_don.id_HD

    @property
    def get_total(self):
        total = self.sach.gia_ban * self.so_luong
        return total

    class Meta:
        verbose_name_plural = 'Chi tiết hóa đơn'

# util model để support hàm debt_report() trong view, KO phải database chính thức
class Debt(models.Model):
    khach_hang = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    no_dau = models.FloatField(null=True)
    phat_sinh = models.FloatField(null=True)
    
    @property
    def no_cuoi(self): return self.no_dau + self.phat_sinh
    
# util model
class Inventory(models.Model):
    ten_sach = models.CharField('Tên sách', max_length=100, null=True)
    ton_dau = models.FloatField(null=True)
    phat_sinh = models.FloatField(null=True)

    @property
    def ton_cuoi(self): return self.ton_dau + self.phat_sinh

QLNhaSach/book/forms.py
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm, Textarea

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomerInfo(ModelForm):
    class Meta:
        model = Person
        fields = ['ho_ten', 'so_dien_thoai', 'email', 'profile_pic', 'dia_chi']
    
    def __init__(self, *args, **kwargs):
        super(CustomerInfo, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['dia_chi'].widget.attrs['cols'] = 10
        self.fields['dia_chi'].widget.attrs['rows'] = 20

class InvoiceForm(ModelForm):
    class Meta:
        model = HoaDon
        fields = ['id_HD', 'ngay_lap_HD']



class CreateBook(ModelForm):
    class Meta:
        model = Sach
        fields = ['ten_sach', 'ngay_nhap', 'so_luong', 'the_loai', 'tac_gia', 'don_gia', 'gia_ban', 'nha_xuat_ban', 'nam_xuat_ban', 'anh_sach', 'mo_ta']

QLNhaSach/book/templates/book/book_entry.html
{% extends 'book/main.html' %}
{% load static %}
{% load humanize %}
{% block title %}Nhập sách{% endblock %}

{% block content %}
<style>
  body{
    text-align: center;
  }
  #messages{
    position: absolute;
    text-align: center;
    color:#000000;
    top: 160px;
    background-color: yellow;
    padding: 5px;
    width: 700px;
    height: 30px;
    border-radius: 30px;
    left: 0;
    right: 0;
    margin-left: auto;
    margin-right: auto;
    font-weight: bold;
    font-size: 15px;
  }

  #id_ten_sach, #id_tac_gia, #id_the_loai, #id_nha_xuat_ban, #id_ngay_nhap, #id_don_gia, #id_nam_xuat_ban, #id_gia_ban, #id_so_luong, #id_mo_ta{
    border-radius: 50px;
    height: 50px;
    padding-left: 20px;
    background-color: rgb(255, 255, 255);
  }

  #id_ten_sach, #id_tac_gia, #id_mo_ta{
    width: 820px;
  }

  #id_the_loai, #id_nha_xuat_ban, #id_ngay_nhap, #id_don_gia, #id_nam_xuat_ban, #id_gia_ban,  #id_so_luong{
    width: 310px;
  }

  #id_mo_ta{
    border-radius: 0;
    border-color: #000000;
    height: 200px;
  }

  input[type=submit]{
    background-color: #04AA6D;
    border: none;
    color: white;
    padding: 8px 16px;
    text-decoration: none;
    font-size: large;
    margin: 4px 2px;
    cursor: pointer; 
}

  .main_title{
    font-size: 30px;
    font-weight: bold;
  }

  .autocomplete {
  /*the container must be positioned relative:*/
  position: relative;
  display: inline-block;
}

.autocomplete-items {
  border: 1px solid #0c0707;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}
.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: rgb(249, 247, 247);
  border-bottom: 1px solid #0e0d0d;
}
.autocomplete-items div:hover {
  /*when hovering an item:*/
  background-color: #e9e9e9;
}
.autocomplete-active {
  /*when navigating through the items using the arrow keys:*/
  background-color: DodgerBlue !important;
  color: #ffffff;
}

.luu_y{
  color: red;
  font-family: 'Courier New', Courier, monospace;
  font-size: 13px;
  font-weight: bold;
  font-style: italic;
  opacity: 70%;
}

.luu_y2{
  color: rgb(44, 43, 43);
  font-family: 'Courier New', Courier, monospace;
  font-size: 13px;
  font-weight: bold;
  font-style: italic;
  opacity: 70%;
}

.form-body {
    /* background:white; */
    padding: 5px 10px;
    width: 85%; 
    margin : auto;
}

.row{
    display: flex;
}

.input-group{
    display: flex;
    flex-direction: column; 
    flex: 1;
    margin-top: 15px;
}

.input-label{
    align-self: flex-start;
    margin-left: 22%;
}
</style>
<div><p class="main_title">Nhập sách mới</p></div>
  <br>
  <hr>
<form autocomplete="off" method="POST" enctype="multipart/form-data" class="form-body">
  {% csrf_token %}
  
  <div class="row">
      <div class="input-group">
        <div class="input-label" style="margin-left: 10%;"><strong>Tên sách</strong></div>
        <div>{{form.ten_sach}}</div>
      </div>
  </div>
  
  <div class="row">
    <div class="input-group">
        <div class="input-label" style="margin-left: 10%;"><strong>Tên tác giả</strong></div>
        <div>{{form.tac_gia}}</div>
    </div>
</div>

  <div class="row">
    <div class="input-group">
        <div class="input-label"><strong>Thể loại</strong></div>
        <div>{{form.the_loai}}</div>
    </div> 
    <div class="input-group">
        <div class="input-label"><strong>Nhà xuất bản</strong></div>
        <div>{{form.nha_xuat_ban}}</div>
    </div>
</div>
 
<div class="row">
    <div class="input-group">
        <div class="input-label"><strong>Ngày nhập</strong><span class="luu_y2">(yyyy-mm-dd)</span></div>
        <div>{{form.ngay_nhap}}</div>
    </div>
         
    <div class="input-group">
        <div class="input-label"><strong>Năm xuất bản</strong></div>
        <div>{{form.nam_xuat_ban}}</div>
    </div>  
</div>
 
<div class="row">
    <div class="input-group">
        <div class="input-label"><strong>Đơn giá</strong></div>
        <div>{{form.don_gia}}</div>      

    </div>
    <div class="input-group">
        <div class="input-label"><strong>Giá bán</strong></div>
        <div>{{form.gia_ban}}</div>
    </div>
</div>

<div class="row">
    <div class="input-group">
        <div class="input-label"><strong>Số lượng</strong><span class="luu_y">(*tối thiểu 150)</span></div>
        <div>{{form.so_luong}}</div>
    </div>
    <div class="input-group">
        <div class="input-label"><strong>Ảnh sách</strong></div>
        <div>{{form.anh_sach}}</div>
    </div>
</div>

  <div class="mt_title input-title"><strong>Mô tả</strong></div>
  {{form.mo_ta}}
  <br>
  
  <div class="submit">
    <input class="btn" type="submit" value="Lưu">
  </div>

  
  {% for message in messages %}
    <p id="messages">{{message}}</p>
  {% endfor %}
</form>

<script>
  function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function (e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false; }
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function (e) {
            /*insert the value for the autocomplete text field:*/
            inp.value = this.getElementsByTagName("input")[0].value;
            /*close the list of autocompleted values,
            (or any other open lists of autocompleted values:*/
            closeAllLists();
          });
          a.appendChild(b);
        }
      }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function (e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }
    /*execute a function when someone clicks in the document:*/
    document.addEventListener("click", function (e) {
      closeAllLists(e.target);
    });
  }

  /*An array containing all the country names in the world:*/
  var Tensach = [{% for s in sach %}'{{s.ten_sach}}', {% endfor %}]
  /*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
  autocomplete(document.getElementById("id_ten_sach"), Tensach);
  var input = document.getElementById('id_ten_sach');
  var onChange = function (evt) {
    var ten = this.value;
    {% for s in sach %}
    var temp = '{{s.ten_sach}}'
    if (temp == ten) {
      document.getElementById('id_ngay_nhap').value = '{{s.ngay_nhap.year}}-{{s.ngay_nhap.month}}-{{s.ngay_nhap.day}}'
      document.getElementById('id_the_loai').value = '{{s.the_loai}}'
      document.getElementById('id_tac_gia').value = '{{s.tac_gia}}'
      document.getElementById('id_don_gia').value = '{{s.don_gia}}'
      document.getElementById('id_gia_ban').value = '{{s.gia_ban}}'
      document.getElementById('id_nha_xuat_ban').value = '{{s.nha_xuat_ban}}'
      document.getElementById('id_nam_xuat_ban').value = '{{s.nam_xuat_ban}}'
      document.getElementById('id_mo_ta').value = '{{s.mo_ta}}'
      console.log('{{s.anh_sach}}')
    }
    {% endfor %}

  };
  input.addEventListener('mousemove', onChange, false);


</script>

{% endblock %}

QLNhaSach/book/templates/book/customer_info.html
{%  extends 'book/main.html' %}
{% load humanize %}

{% block title %}Thông tin{% endblock %}

{% block content %}
<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}

    #id_dia_chi {
    width: 650px;
    height: 30px;
    }
</style>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body">
                <a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Quay lại trang chính</a><br>
                <img class="profile-pic" src="{{request.user.person.profile_pic.url}}" >
            </div>
            {{form.profile_pic}}
        </div>
        <div class="col-md-9">
            <div class="card card-body">
                <div class="card-body">
                    <h6 class="heading-small text-muted mb-4">Thông tin cá nhân</h6>
                    <div class="pl-lg-4">
                    <div class="row">
                    <div class="col-md-12">
                    <div class="form-group focused">
                    <label class="form-control-label" for="id_ho_ten">Họ và Tên</label><br>
                    {{form.ho_ten}}
                <!-- </div>
                </div>
                <div class="col-lg-6">
                <div class="form-group">
                </div>
                </div>
                </div>
                <div class="row">
                <div class="col-lg-6">
                <div class="form-group focused">
                <label class="form-control-label" for="ho">Họ</label>
                <input type="text" id="ho" class="form-control form-control-alternative" placeholder="Họ">
                </div>
                </div>
                <div class="col-lg-6">
                <div class="form-group focused">
                <label class="form-control-label" for="ten">Tên</label>
                <input type="text" id="ten" class="form-control form-control-alternative" placeholder="Tên">
                </div>
                </div>
                </div>
                </div> -->
            </div>
            </div>
            </div>
            </div>
                <hr class="my-4">
                <!-- Address -->
                <h6 class="heading-small text-muted mb-4">Thông tin liên hệ</h6>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-6">
                        <div class="form-group focused">
                        <label class="form-control-label" for="email">Địa chỉ email</label><br>
                        {% comment %} <input type="text" id="email" class="form-control form-control-alternative" placeholder="Địa chỉ email" value=""> {% endcomment %}
                        {{form.email}}
                        </div>
                        </div>
                        <div class="col-lg-6">
                        <div class="form-group focused">
                        <label class="form-control-label" for="so_dien_thoai">Số điện thoại</label><br>
                        {{form.so_dien_thoai}}
                        {% comment %} <input type="text" id="so_dien_thoai" class="form-control form-control-alternative" placeholder="Số điện thoại"> {% endcomment %}
                        </div>
                        </div>
                    </div>
                </div>
                <hr class="my-4">
                <h6 class="heading-small text-muted mb-4">Địa chỉ</h6>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="form-group focused">
                            <label class="form-control-label" for="dia_chi">Địa chỉ nhà</label><br>
                            {{form.dia_chi}}
                        </div>
                    </div>
                </div>
                </div>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-6">
                        <div class="form-group focused">
                            <input style="text-decoration:none;font-family:Gotham,
                            'Helvetica Neue', Helvetica, Arial, sans-serif;color:#ffffff;
                            background:#419941;width:170px;text-align:center;
                            line-height:40px;height:40px;display:block;
                            font-size:15px;" type="submit" value="Lưu">
                        </div>
                        </div>
                        <div class="col-lg-6">
                        <div class="form-group focused">
                            <a style="text-decoration:none;font-family:Gotham,
                            'Helvetica Neue', Helvetica, Arial, sans-serif;color:#ffffff;
                            background:#911818;width:170px;text-align:center;
                            line-height:40px;height:40px;display:block;
                            font-size:15px;" href="\" a>Hủy</a>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

{% endblock %}

QLNhaSach/book/templates/book/delete_book.html
{%  extends 'book/main.html' %}
{% load static %}

<!-- confirm xóa một cuốn sách -->
{% block title %}Xóa sách{% endblock %}

{% block content %}
    <!-- <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete {{item}}</p>

                <form action="{% url 'delete_order' item.id %}" method="POST">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'home' %}">Cancel</a>
                    <input class="btn btn-danger" type="submit" name="Confirm">
                </form> 
            </div>
        </div>
    </div> -->
    
{% endblock %}

QLNhaSach/book/templates/book/pay_debt.html
{%  extends 'book/main.html' %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="page-content container">
    <div class="page-header text-blue-d2">
        <h1 class="page-title text-secondary-d1 text-center">
            Trả nợ
        </h1>

{% if is_debt == True %}
    <div class="table-responsive">
        <table class="table table-striped table-borderless border-0 border-b-2 brc-default-l1">
            <thead class="bg-none bgc-default-tp1">
                <tr class="text-black">
                    <th>Ngày</th>
                    <th>Hóa đơn</th>
                    <th>Nợ</th>
                </tr>
            </thead>

            <tbody class="text-95 text-secondary-d3">
                {% for hd in hd_no %}
                <tr></tr>
                <tr>
                    <td>{{hd.ngay_lap_HD}}</td>
                    <td>{{hd.id_HD}}</td>
                    
                    {% load subtract %}
                    <td>{{hd.tong_tien|subtract:hd.da_tra}}</td>
                    
                    <form method="POST">
                        {% csrf_token %}
                        <th><button class="btn btn-sm btn-info" name="which" type="submit" value="{{ hd.id_HD }}">Thanh toán</button></th>
                </tr> 
                {% endfor %}
                
        </table>
    </div>

{% else %}
    <div class="container text-center">
        <p>Không có thông tin</p>
    </div>
    
{% endif %}

{% endblock content %}